User.create!(
    [
      {
        email: '1@1',
        password: 'qazwsx',
        first_name: '伊都子',
        last_name: '川合',
        first_name_kana: 'イツコ',
        last_name_kana: 'カワイ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '1',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '2@1',
        password: 'qazwsx',
        first_name: '綾奈',
        last_name: '妹尾',
        first_name_kana: 'アヤナ',
        last_name_kana: 'セノオ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '1',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '3@1',
        password: 'qazwsx',
        first_name: '雛乃',
        last_name: '本多',
        first_name_kana: 'ヒナノ',
        last_name_kana: 'ホンダ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '7',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '4@1',
        password: 'qazwsx',
        first_name: '憲司',
        last_name: '花田',
        first_name_kana: 'ケンジ',
        last_name_kana: 'ハナダ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '1',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '5@1',
        password: 'qazwsx',
        first_name: '昌二',
        last_name: '佐野',
        first_name_kana: 'ショウジ',
        last_name_kana: 'サノ',
        prefecture_code: '9',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '1',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '6@1',
        password: 'qazwsx',
        first_name: '政治',
        last_name: '田中',
        first_name_kana: 'セイジ',
        last_name_kana: 'タナカ',
        prefecture_code: '12',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '1',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '7@1',
        password: 'qazwsx',
        first_name: '佳乃',
        last_name: '吾妻',
        first_name_kana: 'ヨシノ',
        last_name_kana: 'アズマ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '12',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '8@1',
        password: 'qazwsx',
        first_name: '博一',
        last_name: '長島',
        first_name_kana: 'ヒロカズ',
        last_name_kana: 'ナガシマ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '11',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '9@1',
        password: 'qazwsx',
        first_name: '吉明',
        last_name: '三村',
        first_name_kana: 'ヨシアキ',
        last_name_kana: 'ミムラ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '14',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      },
      {
        email: '10@1',
        password: 'qazwsx',
        first_name: '隼',
        last_name: '中塚',
        first_name_kana: 'ハヤト',
        last_name_kana: 'ナカツカ',
        prefecture_code: '1',
        phone_number: '090-0000-0000',
        personality: 'true',
        category_id: '17',
        hope_prefecture_code: '1',
        pr: 'この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。',
        is_deleted: 'FALSE'
      }
      
    ]
  )